[project]
name = "nginx-web-backend"
version = "0.1.0"
description = "Nginx Web Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crossplane>=0.5.8",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.1",
]
