[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crossplane>=0.5.8",
    "fastapi>=0.115.12",
]
